[package]
name = "sundial-gc"
version = "0.1.0"
authors = ["host"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static_assertions = "1.1.0"
lazy_static = "1.4.0"
